services:
  db:
    image: postgres:18.0-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: local
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    ports: 
      - "3000:3000"
    restart: always
    depends_on:
      - db
    environment:
      NODE_ENV: DEV
      JWT_SECRET: test
      RUN_MIGRATIONS: true
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DATABASE: local


volumes:
  pgdata:
